apiVersion: v1
kind: ConfigMap
metadata:
  name: html
  namespace: myapp
data:
  index.html: |
    <html>
      <body style="background-color:#e6ffe6">
        <h1>🚀 This is PROD</h1>
        <h2>Caddy Web Server</h2>
      </body>
    </html>

