apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


configMapGenerator:
  - name: candy-web-config
    files:
      - index.html=index.html

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - sealedsecret.yaml   

